// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjJmB5sVbWZAmCrb3hMfdORbUtuiCsnYo',
    appId: '1:3226290479:web:46adb4739a2df23f6bb9da',
    messagingSenderId: '3226290479',
    projectId: 'movies-3adcf',
    authDomain: 'movies-3adcf.firebaseapp.com',
    storageBucket: 'movies-3adcf.appspot.com',
    measurementId: 'G-3MW754F68G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkkuxfyTu7f75G2qnQZLmUW5oCnLg7mNU',
    appId: '1:3226290479:android:8f4b69e0973f8cda6bb9da',
    messagingSenderId: '3226290479',
    projectId: 'movies-3adcf',
    storageBucket: 'movies-3adcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBojAX-oOopsv0UxdZONxaJGe8luTi4eVk',
    appId: '1:3226290479:ios:7e621dca6301e57a6bb9da',
    messagingSenderId: '3226290479',
    projectId: 'movies-3adcf',
    storageBucket: 'movies-3adcf.appspot.com',
    iosClientId: '3226290479-tlij9ouletlagprufefcmroaphp2cf2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBojAX-oOopsv0UxdZONxaJGe8luTi4eVk',
    appId: '1:3226290479:ios:7e621dca6301e57a6bb9da',
    messagingSenderId: '3226290479',
    projectId: 'movies-3adcf',
    storageBucket: 'movies-3adcf.appspot.com',
    iosClientId: '3226290479-tlij9ouletlagprufefcmroaphp2cf2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
